/**
 * PDF integrity end-to-end tests.
 *
 * Verifies that the PDF buffer generated by the full pipeline:
 * 1. Starts with the %PDF- magic bytes.
 * 2. Has substantial size (> 10 KB).
 * 3. Is a Buffer (not a string or undefined).
 *
 * These tests use Puppeteer and require a longer timeout.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { buildApp } from '../app';
import { rateLimiter } from '../core/rate-limit/rate-limit.service';
import { resetMetrics, getCounterValue, METRIC } from '../metrics/metrics.service';
import { shutdownPdfService } from '../rendering/pdf/pdf.service';
import { seedPages, JSON_REPORT_BODY } from './_helpers';

const app = buildApp();
const TIMEOUT = 45_000; // generous — Puppeteer cold start

beforeAll(async () => {
    seedPages();
    await app.ready();
    resetMetrics();
    rateLimiter.reset('tenant-alpha');
});

afterAll(async () => {
    await app.close();
    await shutdownPdfService();
});

const POST_PDF = (patientId: string) =>
    app.inject({
        method: 'POST',
        url: '/reports/generate',
        headers: { 'Content-Type': 'application/json' },
        payload: JSON.stringify({
            ...JSON_REPORT_BODY,
            output: 'pdf',
            reportData: { ...JSON_REPORT_BODY.reportData, patientId },
        }),
    });

describe('PDF integrity', () => {
    it('returns Content-Type application/pdf', async () => {
        const res = await POST_PDF('PAT-PDF-001');
        expect(res.statusCode).toBe(200);
        expect(res.headers['content-type']).toContain('application/pdf');
    }, TIMEOUT);

    it('response starts with PDF magic bytes (%PDF-)', async () => {
        const res = await POST_PDF('PAT-PDF-002');
        expect(res.statusCode).toBe(200);

        const rawPayload = res.rawPayload;
        const magic = rawPayload.subarray(0, 5).toString('ascii');
        expect(magic).toBe('%PDF-');
    }, TIMEOUT);

    it('PDF buffer is larger than 10 KB', async () => {
        const res = await POST_PDF('PAT-PDF-003');
        expect(res.statusCode).toBe(200);
        expect(res.rawPayload.length).toBeGreaterThan(10_000);
    }, TIMEOUT);

    it('sets Content-Disposition header', async () => {
        const res = await POST_PDF('PAT-PDF-004');
        expect(res.statusCode).toBe(200);
        expect(res.headers['content-disposition']).toContain('tenant-alpha-report.pdf');
    }, TIMEOUT);

    it('second identical PDF request returns cached PDF', async () => {
        resetMetrics();
        rateLimiter.reset('tenant-alpha');

        const PATIENT = 'PAT-PDF-CACHE';

        // First: generate + cache
        const res1 = await POST_PDF(PATIENT);
        expect(res1.statusCode).toBe(200);
        expect(getCounterValue(METRIC.PDF_GENERATION_TOTAL, { source: 'json' })).toBe(1);

        // Second: cache hit (PDF already stored)
        const res2 = await POST_PDF(PATIENT);
        expect(res2.statusCode).toBe(200);

        // PDF counter should NOT increment again — served from cache
        expect(getCounterValue(METRIC.PDF_GENERATION_TOTAL, { source: 'json' })).toBe(1);

        // But both buffers should start with %PDF-
        expect(res1.rawPayload.subarray(0, 5).toString('ascii')).toBe('%PDF-');
        expect(res2.rawPayload.subarray(0, 5).toString('ascii')).toBe('%PDF-');
    }, TIMEOUT);

    it('increments PDF generation counter', async () => {
        resetMetrics();
        rateLimiter.reset('tenant-alpha');
        await POST_PDF('PAT-PDF-COUNTER');
        expect(getCounterValue(METRIC.PDF_GENERATION_TOTAL, { source: 'json' })).toBeGreaterThanOrEqual(1);
    }, TIMEOUT);
});
