/**
 * Default Profile Mapping
 *
 * Maps standard test names to their health profile category.
 * e.g. "Total Cholesterol" → "Lipid Profile"
 *
 * Generated from: NG Test list 26 - Sheet 1.csv
 * Total entries: 1248
 * Total profiles: 43
 *
 * Profiles: Allergy Panel, Anemia Studies, Arthritis Screening, Autoimmune Disorders, BMI & BP, Bacterial Infections, Blood Clotting, Blood Counts, Blood Disorder, Blood Group, Bone Health, COVID, Cancer Profile, Cardiac Profile, Covid, Diabetes Monitoring, Electrolyte Profile, Heart Assure, Hemoglobin Electrophoresis, Hepatitis, Hormones, Hypertension, Immunity, Infectious Diseases, Inflammation, Kidney Profile, Lipid Profile, Liver Profile, Malaria Profile, Mineral Profile, Neurological Disorders, Pancreas, Prothrombin Time, STD Profile, Semen Analysis, Semen Culture and Sensitivity, Stool Analysis, Thyroid Profile, Toxic elements, Tumour Marker Test, Urinalysis, Viral Infections, Vitamin Profile
 */
export const DEFAULT_PROFILE_MAPPING: Record<string, string> = {

  // ── Allergy Panel ──
  'ALLERGY INDIVIDUAL MARKER PEANUT': 'Allergy Panel',
  'ALLERGY, INDIVIDUAL MARKER, BUCKWHEAT': 'Allergy Panel',
  'Allergen-ACTH': 'Allergy Panel',
  'Allergen-Gluten': 'Allergy Panel',
  'Allergy Acacia Spp (Acacia)': 'Allergy Panel',
  'Allergy Acarus Siro (Flour Mite) By EIA': 'Allergy Panel',
  'Allergy Acetylcysteine': 'Allergy Panel',
  'Allergy Agrostis Stolonifera (Bentgrass) By EIA': 'Allergy Panel',
  'Allergy Amaranthus Retroflexus (Common Pigweed)': 'Allergy Panel',
  'Allergy Ambroxol': 'Allergy Panel',
  'Allergy Anise': 'Allergy Panel',
  'Allergy Anthoxanthum Odoratum (Sweet Vernal Grass)': 'Allergy Panel',
  'Allergy Apricot': 'Allergy Panel',
  'Allergy Ascaris Lumbricoides': 'Allergy Panel',
  'Allergy Aspirin': 'Allergy Panel',
  'Allergy Azithromycin': 'Allergy Panel',
  'Allergy Basil': 'Allergy Panel',
  'Allergy Beet': 'Allergy Panel',
  'Allergy Benzocaine': 'Allergy Panel',
  'Allergy Black': 'Allergy Panel',
  'Allergy Books Dust': 'Allergy Panel',
  'Allergy Brassica Napus (Rape)': 'Allergy Panel',
  'Allergy Broccoli': 'Allergy Panel',
  'Allergy Bromhexine': 'Allergy Panel',
  'Allergy Budgerigar Dropping': 'Allergy Panel',
  'Allergy Budgerigar Feathers': 'Allergy Panel',
  'Allergy Budgerigar Serum Proteins': 'Allergy Panel',
  'Allergy Canarian Feathers': 'Allergy Panel',
  'Allergy Cardamon': 'Allergy Panel',
  'Allergy Cherry': 'Allergy Panel',
  'Allergy Chicken Droppings': 'Allergy Panel',
  'Allergy Chicken Feathers': 'Allergy Panel',
  'Allergy Chloramphenicol': 'Allergy Panel',
  'Allergy Clarithromycin': 'Allergy Panel',
  'Allergy Co-Trimoxazole': 'Allergy Panel',
  'Allergy Cobalamin': 'Allergy Panel',
  'Allergy Cranberry': 'Allergy Panel',
  'Allergy Curcuma': 'Allergy Panel',
  'Allergy Curry': 'Allergy Panel',
  'Allergy Dactylis Glomerata (Cocksfoot)': 'Allergy Panel',
  'Allergy Date': 'Allergy Panel',
  'Allergy Drug Insulin Human By Immuno CAP': 'Allergy Panel',
  'Allergy Duck Feathers': 'Allergy Panel',
  'Allergy Duck Meat': 'Allergy Panel',
  'Allergy Euroglyphus Maynei (House Mite)': 'Allergy Panel',
  'Allergy Fennel': 'Allergy Panel',
  'Allergy Festuca Elatior (Meadow Fescue)': 'Allergy Panel',
  'Allergy Fig': 'Allergy Panel',
  'Allergy Flax Seed': 'Allergy Panel',
  'Allergy Flaxseed': 'Allergy Panel',
  'Allergy Gelatin': 'Allergy Panel',
  'Allergy Gentamycin': 'Allergy Panel',
  'Allergy Glycyphagus Domesticus (Store Mite)': 'Allergy Panel',
  'Allergy Goose Feathers': 'Allergy Panel',
  'Allergy Helminthosporium Halodes': 'Allergy Panel',
  'Allergy Henna': 'Allergy Panel',
  'Allergy Heterocera Mix (Moth)': 'Allergy Panel',
  'Allergy Housefly Musca Domestica': 'Allergy Panel',
  'Allergy Ibuprofen': 'Allergy Panel',
  'Allergy Jute': 'Allergy Panel',
  'Allergy Ketoprofen': 'Allergy Panel',
  'Allergy Kiwi': 'Allergy Panel',
  'Allergy Lentil': 'Allergy Panel',
  'Allergy Lentil (Dal)': 'Allergy Panel',
  'Allergy Lepidoglyphus Destructor (Hay Mite)': 'Allergy Panel',
  'Allergy Lidocaine': 'Allergy Panel',
  'Allergy Lobster': 'Allergy Panel',
  'Allergy Lychee': 'Allergy Panel',
  'Allergy Mackerel': 'Allergy Panel',
  'Allergy Metronidazole': 'Allergy Panel',
  'Allergy Mint': 'Allergy Panel',
  'Allergy Morus Alba (Red Mulberry)': 'Allergy Panel',
  'Allergy Mouse (Epithelium, Serum, Urine, Protein)': 'Allergy Panel',
  'Allergy Mucor': 'Allergy Panel',
  'Allergy Mucor Racemosus': 'Allergy Panel',
  'Allergy Naproxen': 'Allergy Panel',
  'Allergy Nart V1 Artemisia Vulgaris (Mugwort)': 'Allergy Panel',
  'Allergy Neomycin': 'Allergy Panel',
  'Allergy Olive': 'Allergy Panel',
  'Allergy Oregano': 'Allergy Panel',
  'Allergy Oxacillin': 'Allergy Panel',
  'Allergy P4 Anisakis': 'Allergy Panel',
  'Allergy Paracetamol': 'Allergy Panel',
  'Allergy Parsley': 'Allergy Panel',
  'Allergy Peach': 'Allergy Panel',
  'Allergy Pear': 'Allergy Panel',
  'Allergy Penicilloyl G': 'Allergy Panel',
  'Allergy Penicilloyl V': 'Allergy Panel',
  'Allergy Phleum Pratense (Timothy) By EIA': 'Allergy Panel',
  'Allergy Phoma Betae': 'Allergy Panel',
  'Allergy Phosphomycin': 'Allergy Panel',
  'Allergy Phragmites Communis (Common Reed) By EIA': 'Allergy Panel',
  'Allergy Pig Epithelium': 'Allergy Panel',
  'Allergy Pigeon Droppings': 'Allergy Panel',
  'Allergy Pigeon Feathers': 'Allergy Panel',
  'Allergy Plum': 'Allergy Panel',
  'Allergy Pomegranate': 'Allergy Panel',
  'Allergy Pork': 'Allergy Panel',
  'Allergy Prilocaine': 'Allergy Panel',
  'Allergy Prosopis Juliflora (Mesquite)': 'Allergy Panel',
  'Allergy Pumpkin': 'Allergy Panel',
  'Allergy Pumpkin Seed': 'Allergy Panel',
  'Allergy Pyridoxine': 'Allergy Panel',
  'Allergy Rabbit Epithelium': 'Allergy Panel',
  'Allergy Raisin': 'Allergy Panel',
  'Allergy Rhizopus Nigricans': 'Allergy Panel',
  'Allergy Rifampicin': 'Allergy Panel',
  'Allergy Rosemary': 'Allergy Panel',
  'Allergy Saffron': 'Allergy Panel',
  'Allergy Salix Caprea (Willow)': 'Allergy Panel',
  'Allergy Salmon': 'Allergy Panel',
  'Allergy Sardine': 'Allergy Panel',
  'Allergy Semolina': 'Allergy Panel',
  'Allergy Sheep Epithelium': 'Allergy Panel',
  'Allergy Sorghum Halepense (Johnson Grass)': 'Allergy Panel',
  'Allergy Tea': 'Allergy Panel',
  'Allergy Thiamine': 'Allergy Panel',
  'Allergy Thyme': 'Allergy Panel',
  'Allergy Toxocara Canis': 'Allergy Panel',
  'Allergy Trichoderma Viride': 'Allergy Panel',
  'Allergy Tuna': 'Allergy Panel',
  'Allergy Turkey': 'Allergy Panel',
  'Allergy Turkey Feathers': 'Allergy Panel',
  'Allergy Turnip': 'Allergy Panel',
  'Allergy Tyrophagus Putresentiae (Cheese Mite)': 'Allergy Panel',
  'Allergy Vanilla': 'Allergy Panel',
  'Allergy Vespula Germanica (Common Wasp - Yellow Jacket)': 'Allergy Panel',
  'Allergy Walnut': 'Allergy Panel',
  'Allergy White Bean': 'Allergy Panel',
  'Allergy Whole': 'Allergy Panel',
  'Allergy Xanthium Commune (Cocklebur)': 'Allergy Panel',
  'Allergy Yogurt': 'Allergy Panel',
  'Allergy: Carp FISH': 'Allergy Panel',
  'Allergy: Cashew (Kaju) By ImmunoCAP': 'Allergy Panel',
  'Allergy: Food Basil By ImmunoCAP': 'Allergy Panel',
  'Allergy: Mulberry (Shahtoot) By ImmunoCAP': 'Allergy Panel',
  'Allergy: Olive By ImmunoCAP': 'Allergy Panel',
  'Allergy: Phadiatop (< 5 Years)': 'Allergy Panel',
  'Allergy: Poppy': 'Allergy Panel',
  'Allergy: Ragweed': 'Allergy Panel',
  'Almond': 'Allergy Panel',
  'Alpha Feto Protein - CSF': 'Allergy Panel',
  'Alternaria Tenuis': 'Allergy Panel',
  'Amoxicillin': 'Allergy Panel',
  'Apple': 'Allergy Panel',
  'Aspergillus Niger': 'Allergy Panel',
  'Baker\'s Yeast Allergy': 'Allergy Panel',
  'Banana Allergy': 'Allergy Panel',
  'Bananas': 'Allergy Panel',
  'Beans': 'Allergy Panel',
  'Beef': 'Allergy Panel',
  'Bermuda Grass': 'Allergy Panel',
  'Black Pepper': 'Allergy Panel',
  'Cabbage': 'Allergy Panel',
  'Carrot Allergy': 'Allergy Panel',
  'Cashewnut': 'Allergy Panel',
  'Cat Dander': 'Allergy Panel',
  'Cauliflowers': 'Allergy Panel',
  'Celery': 'Allergy Panel',
  'Cephalosporin': 'Allergy Panel',
  'Cheese': 'Allergy Panel',
  'Chenopodium Album': 'Allergy Panel',
  'Chicken Allergy': 'Allergy Panel',
  'Chocolate Allergy': 'Allergy Panel',
  'Cinnamons': 'Allergy Panel',
  'Cladosporium hebarum': 'Allergy Panel',
  'Cloves': 'Allergy Panel',
  'Cloxacillin': 'Allergy Panel',
  'Coconut': 'Allergy Panel',
  'Codfish Allergy': 'Allergy Panel',
  'Coffees': 'Allergy Panel',
  'Corianders': 'Allergy Panel',
  'Cotton Fibre': 'Allergy Panel',
  'Cow Dander': 'Allergy Panel',
  'Cow Milk Allergy': 'Allergy Panel',
  'Crab': 'Allergy Panel',
  'Cucumbers': 'Allergy Panel',
  'Curd': 'Allergy Panel',
  'Cynodon Dactylon': 'Allergy Panel',
  'Derm Farinae': 'Allergy Panel',
  'Diclofenac': 'Allergy Panel',
  'Dog Dander': 'Allergy Panel',
  'Doxycycline': 'Allergy Panel',
  'Egg White Allergy': 'Allergy Panel',
  'Egg Yolk Allergy': 'Allergy Panel',
  'Eggplant': 'Allergy Panel',
  'Erythromycin': 'Allergy Panel',
  'Eucalyptus': 'Allergy Panel',
  'Fish (cod)': 'Allergy Panel',
  'Garlic': 'Allergy Panel',
  'Ginger': 'Allergy Panel',
  'Goat Dander': 'Allergy Panel',
  'Grapes': 'Allergy Panel',
  'Guavas': 'Allergy Panel',
  'HLA – ABACAVIR HYPERSENSTIVITY': 'Allergy Panel',
  'Hay Dust': 'Allergy Panel',
  'Honey Bee': 'Allergy Panel',
  'House Dust': 'Allergy Panel',
  'Lamb Allergy': 'Allergy Panel',
  'Latex': 'Allergy Panel',
  'Lemons': 'Allergy Panel',
  'Lettuce': 'Allergy Panel',
  'Maize': 'Allergy Panel',
  'Mango Allergy': 'Allergy Panel',
  'Melons': 'Allergy Panel',
  'Mosquito': 'Allergy Panel',
  'Mugwort Sagebrush': 'Allergy Panel',
  'Mushroom': 'Allergy Panel',
  'Mustard': 'Allergy Panel',
  'Mutton': 'Allergy Panel',
  'Nut Mix Allergy': 'Allergy Panel',
  'Nutmeg': 'Allergy Panel',
  'Oat': 'Allergy Panel',
  'Ofloxacin': 'Allergy Panel',
  'Onion Allergy': 'Allergy Panel',
  'Orange Allergy': 'Allergy Panel',
  'Papaya': 'Allergy Panel',
  'Pea': 'Allergy Panel',
  'Peanut Allergy': 'Allergy Panel',
  'Pearl Millet': 'Allergy Panel',
  'Penicillin': 'Allergy Panel',
  'Phadiatop': 'Allergy Panel',
  'Phadiatop Allergen screening -Adult': 'Allergy Panel',
  'Phinf  Top': 'Allergy Panel',
  'Pineapple': 'Allergy Panel',
  'Piroxicam': 'Allergy Panel',
  'Pistachio': 'Allergy Panel',
  'Potato': 'Allergy Panel',
  'Radishes': 'Allergy Panel',
  'Rice': 'Allergy Panel',
  'Rye Grass': 'Allergy Panel',
  'Sesame': 'Allergy Panel',
  'Sheep Wool': 'Allergy Panel',
  'Shrimp': 'Allergy Panel',
  'Shrimp/Prawn Allergy': 'Allergy Panel',
  'Silk': 'Allergy Panel',
  'Soy Bean Allergy': 'Allergy Panel',
  'Spinach': 'Allergy Panel',
  'Straw Berry': 'Allergy Panel',
  'Strawberry Allergy': 'Allergy Panel',
  'Streptomycin': 'Allergy Panel',
  'Sunflower': 'Allergy Panel',
  'Tobacco': 'Allergy Panel',
  'Tomato Allergy': 'Allergy Panel',
  'Walnut (Hazel)': 'Allergy Panel',
  'Wheat Flour Allergy': 'Allergy Panel',
  'Wood Mix': 'Allergy Panel',
  'Yeast': 'Allergy Panel',
  'llergy: Pear (Nashpati) By ImmunoCAP': 'Allergy Panel',

  // ── Anemia Studies ──
  '% Saturation Transferrin': 'Anemia Studies',
  'Content Haemoglobin (CH)': 'Anemia Studies',
  'Erythropoietin': 'Anemia Studies',
  'Ferritin': 'Anemia Studies',
  'G6PD (Qualitative)': 'Anemia Studies',
  'G6PD (Quantitative)': 'Anemia Studies',
  'Glucose-6-Phosphate Dehydrogenase Enzyme Activity~G6PD Deficiency': 'Anemia Studies',
  'Iron': 'Anemia Studies',
  'Methaemoglobin Estimation': 'Anemia Studies',
  'Porphobilinogen (PBG) Quantitative, 24 Hrs Urine': 'Anemia Studies',
  'Porphobilinogen (PBG) Quantitative, Spot Urine': 'Anemia Studies',
  'Porphyrins Qualitative, Spot Urine': 'Anemia Studies',
  'RBC (Synovial Fluid)': 'Anemia Studies',
  'SICKLING, SCREENING TEST': 'Anemia Studies',
  'Serum Folate': 'Anemia Studies',
  'Sickle Cell Solubility Test-Sickling phenomenon': 'Anemia Studies',
  'Soluble Transferrin Receptor( STFR)': 'Anemia Studies',
  'TIBC': 'Anemia Studies',
  'Transferrin Serum': 'Anemia Studies',
  'UIBC': 'Anemia Studies',

  // ── Arthritis Screening ──
  'ASO (quantitative)': 'Arthritis Screening',
  'Ionized Calcium': 'Arthritis Screening',
  'Non Ionized Calcium': 'Arthritis Screening',
  'RA factor (descriptive)': 'Arthritis Screening',
  'RA factor (quantitative)': 'Arthritis Screening',

  // ── Autoimmune Disorders ──
  'ANA (Antinuclear Antibody)-Screen': 'Autoimmune Disorders',
  'ANA-Titer': 'Autoimmune Disorders',
  'ANTI CCP (CYCLIC CITRULLINATED PEPTIDE)': 'Autoimmune Disorders',
  'ANTI SOLUBLE LIVER ANTIGEN (SLA)': 'Autoimmune Disorders',
  'Anti CCP': 'Autoimmune Disorders',
  'Anti Cardiolipin IgA': 'Autoimmune Disorders',
  'Anti Cardiolipin IgG': 'Autoimmune Disorders',
  'Anti Cardiolipin IgM': 'Autoimmune Disorders',
  'Anti DNA Abs.': 'Autoimmune Disorders',
  'Anti Double Stranded DNA ( dsDNA-IgG)': 'Autoimmune Disorders',
  'Anti Double Stranded DNA (DsDNA) BY IFA': 'Autoimmune Disorders',
  'Anti Epidermal (Pemphigus) Antibody By IF': 'Autoimmune Disorders',
  'Anti Nuclear Antibody by IFA': 'Autoimmune Disorders',
  'Anti-Phospholipid (IgG)': 'Autoimmune Disorders',
  'Anti-Phospholipid (IgM)': 'Autoimmune Disorders',
  'Anti-TPO': 'Autoimmune Disorders',
  'Anti-Tissue Transglutaminase IgA': 'Autoimmune Disorders',
  'Antimitochondrial M2 Antibody.': 'Autoimmune Disorders',
  'Bullous Pemphigoid 180': 'Autoimmune Disorders',
  'Bullous Pemphigoid 230': 'Autoimmune Disorders',
  'C3 COMPLEMENT, SERUM': 'Autoimmune Disorders',
  'C4 COMPLEMENT, SERUM': 'Autoimmune Disorders',
  'CENP-B': 'Autoimmune Disorders',
  'CH-50Complement, total': 'Autoimmune Disorders',
  'Centromere Antibody IgG': 'Autoimmune Disorders',
  'Coombs Test (Indirect)': 'Autoimmune Disorders',
  'Degeneration (Synovial Fluid)': 'Autoimmune Disorders',
  'Desmoglein I Antibody': 'Autoimmune Disorders',
  'Desmoglein III Antibody': 'Autoimmune Disorders',
  'GAD-65 (GLUTAMIC ACID DECARBOXYLASE- 65) ,SERUM': 'Autoimmune Disorders',
  'Glucose (Synovial Fluid)': 'Autoimmune Disorders',
  'HLA B27 Detection': 'Autoimmune Disorders',
  'Histone Antibody': 'Autoimmune Disorders',
  'Histones': 'Autoimmune Disorders',
  'Jo - 1': 'Autoimmune Disorders',
  'Jo-1 Antibody IgG': 'Autoimmune Disorders',
  'Ku': 'Autoimmune Disorders',
  'LC-1 Antibody': 'Autoimmune Disorders',
  'Lupus Anticoagulant': 'Autoimmune Disorders',
  'M2-3E (BPO) Antibody.': 'Autoimmune Disorders',
  'MPO p-ANCA': 'Autoimmune Disorders',
  'Mi-2': 'Autoimmune Disorders',
  'Monocytes (Synovial Fluid)': 'Autoimmune Disorders',
  'Nucleosomes': 'Autoimmune Disorders',
  'Ovarian Antibody': 'Autoimmune Disorders',
  'PCNA': 'Autoimmune Disorders',
  'PM-Scl': 'Autoimmune Disorders',
  'PML Antibody': 'Autoimmune Disorders',
  'PR3 by EIAc-ANCA': 'Autoimmune Disorders',
  'Rh Antibody Titre': 'Autoimmune Disorders',
  'Rheumatoid Factors ,Qualitative': 'Autoimmune Disorders',
  'Rib- P Protein': 'Autoimmune Disorders',
  'Ro- 52': 'Autoimmune Disorders',
  'Ro-52 Antibody': 'Autoimmune Disorders',
  'SLA/LP Antibody': 'Autoimmune Disorders',
  'SS-A(RO)': 'Autoimmune Disorders',
  'SS-B/La': 'Autoimmune Disorders',
  'SSA - A (Soluble Substance A) IgG': 'Autoimmune Disorders',
  'SSB - B Antibody': 'Autoimmune Disorders',
  'SSB - La (Soluble Substance B) IgG': 'Autoimmune Disorders',
  'Scl - 70': 'Autoimmune Disorders',
  'Scl - 70 Antibody IgG': 'Autoimmune Disorders',
  'Sm': 'Autoimmune Disorders',
  'Sm Antibody IgG': 'Autoimmune Disorders',
  'SnRNP  ANTIBODIES': 'Autoimmune Disorders',
  'Sp100 Antibody': 'Autoimmune Disorders',
  'Total Proteins (Synovial Fluid)': 'Autoimmune Disorders',
  'U1-nRNP/Sm': 'Autoimmune Disorders',
  'Volume (Synovial Fluid)': 'Autoimmune Disorders',
  'anti- liver-kidney microsomal IgG antibodies': 'Autoimmune Disorders',
  'anti- liver-kidney microsomal IgG antibodies.': 'Autoimmune Disorders',
  'anti-Glomerular Basement Membrane protein (GBM)': 'Autoimmune Disorders',
  'c-ANCA': 'Autoimmune Disorders',
  'ds-DNA': 'Autoimmune Disorders',
  'gp210 Antibody': 'Autoimmune Disorders',
  'p-ANCA': 'Autoimmune Disorders',

  // ── BMI & BP ──
  'Blood Pressure': 'BMI & BP',
  'Blood pressure': 'BMI & BP',
  'Body Mass Index(BMI)': 'BMI & BP',
  'Body Temperature': 'BMI & BP',
  'Diastolic': 'BMI & BP',
  'Height': 'BMI & BP',
  'Pulse': 'BMI & BP',
  'Systolic': 'BMI & BP',
  'Weight': 'BMI & BP',

  // ── Bacterial Infections ──
  'Gram Stain': 'Bacterial Infections',
  'Helicobacter Antigen in Stool': 'Bacterial Infections',
  'Helicobacter Pylori Abs.(IgG)': 'Bacterial Infections',
  'Helicobacter Pylori Abs.(IgM)': 'Bacterial Infections',
  'Typhidot': 'Bacterial Infections',
  'Urea Breath Test': 'Bacterial Infections',
  'WIDAL TEST (SLIDE METHOD)': 'Bacterial Infections',

  // ── Blood Clotting ──
  'APTT': 'Blood Clotting',
  'Activated Partial Thromboplastin Time': 'Blood Clotting',
  'Anti Phospholipid IgA': 'Blood Clotting',
  'Anti Thrombin III Activity': 'Blood Clotting',
  'Beta-2-Glycoprotein 1 -IgG': 'Blood Clotting',
  'Beta-2-Glycoprotein 1 -IgM': 'Blood Clotting',
  'Beta-2-Glycoprotein IgM Antibody': 'Blood Clotting',
  'Cardiolipin Antibody ACL-IgA': 'Blood Clotting',
  'Control (MNAPTT)': 'Blood Clotting',
  'D-Dimer': 'Blood Clotting',
  'DRVVT Screening': 'Blood Clotting',
  'FACTOR VII FUNCTIONAL': 'Blood Clotting',
  'FACTOR VIII FUNCTIONAL': 'Blood Clotting',
  'FACTOR X FUNCTIONAL': 'Blood Clotting',
  'FIBRINOGEN DEGRADATION PRODUCTS (FDP), BLOOD': 'Blood Clotting',
  'Factor IX Functional': 'Blood Clotting',
  'Factor XI Activity': 'Blood Clotting',
  'Lupus DRVV Screen (Control)': 'Blood Clotting',
  'Lupus DRVV Screen (Ratio)': 'Blood Clotting',
  'Lupus DRVV Screen (Test)': 'Blood Clotting',
  'Mixing Studies Inhibitors': 'Blood Clotting',
  'PT TEST': 'Blood Clotting',
  'Phosphatidylserine IgM Antibody': 'Blood Clotting',
  'Protein C Activity': 'Blood Clotting',
  'Prothrombin Gene Mutation Analysis (Factor II)': 'Blood Clotting',
  'Screen Ratio': 'Blood Clotting',
  'Thrombin Time': 'Blood Clotting',

  // ── Blood Counts ──
  'ABNORMAL CELLS': 'Blood Counts',
  'ABSOLUTE RETICULOCYTE COUNT': 'Blood Counts',
  'AMH2': 'Blood Counts',
  'Abs. Basophil Count': 'Blood Counts',
  'Abs. Eosinophil Count': 'Blood Counts',
  'Abs. Immature Granulocytes': 'Blood Counts',
  'Abs. Lymphocyte Count': 'Blood Counts',
  'Abs. Monocyte Count': 'Blood Counts',
  'Abs. Neutrophil Count': 'Blood Counts',
  'Absolute Granulocytes count': 'Blood Counts',
  'Absolute Large Unstained Cell': 'Blood Counts',
  'Absolute Nucleated red blood cells': 'Blood Counts',
  'Anti Nuclear Antibodies (ANA)': 'Blood Counts',
  'Atypical Cell': 'Blood Counts',
  'Atypical Lymphocytes (LUC)': 'Blood Counts',
  'Atypical Lymphoid Cell': 'Blood Counts',
  'Atypical Monocytoid cell': 'Blood Counts',
  'Atypical Plasma Cell': 'Blood Counts',
  'Band Cells': 'Blood Counts',
  'Basophils': 'Blood Counts',
  'Blast Cells': 'Blood Counts',
  'C-Peptide (Fasting)': 'Blood Counts',
  'C-Peptide (Post prandial)': 'Blood Counts',
  'CORRECTED RETICULOCYTE COUNT': 'Blood Counts',
  'Corrected TLC': 'Blood Counts',
  'ESR': 'Blood Counts',
  'Eosinophils': 'Blood Counts',
  'Granulocytes': 'Blood Counts',
  'HDW (Haemoglobin Distribution Width)': 'Blood Counts',
  'HEMOPARASITES': 'Blood Counts',
  'Haematocrit': 'Blood Counts',
  'Haemoglobin': 'Blood Counts',
  'IMMATURE PLATELET FRACTION': 'Blood Counts',
  'IgA': 'Blood Counts',
  'IgG': 'Blood Counts',
  'Immature Granulocytes': 'Blood Counts',
  'LIC#': 'Blood Counts',
  'LIC%': 'Blood Counts',
  'Large Unstained Cell': 'Blood Counts',
  'Lymphoblasts': 'Blood Counts',
  'Lymphocyte-Monocyte Ratio': 'Blood Counts',
  'Lymphocytes': 'Blood Counts',
  'MCH': 'Blood Counts',
  'MCHC': 'Blood Counts',
  'MCV': 'Blood Counts',
  'MENTZER INDEX': 'Blood Counts',
  'MPV': 'Blood Counts',
  'MYELOBLAST': 'Blood Counts',
  'Mean Platelet Component (MPC)': 'Blood Counts',
  'Mean Platelet Mass (MPM)': 'Blood Counts',
  'Meta-Myelocytes': 'Blood Counts',
  'Mixed Cells': 'Blood Counts',
  'Monocytes': 'Blood Counts',
  'Myelocytes': 'Blood Counts',
  'Neutrophil Lymphocyte Ratio': 'Blood Counts',
  'Neutrophil lymhocyte ratio': 'Blood Counts',
  'Neutrophils': 'Blood Counts',
  'Nucleated red blood cells': 'Blood Counts',
  'Other Leukocyte': 'Blood Counts',
  'P-LCC': 'Blood Counts',
  'P-LCR': 'Blood Counts',
  'PCT': 'Blood Counts',
  'PDW': 'Blood Counts',
  'PDW - SD': 'Blood Counts',
  'PERIPHERAL SMEAR': 'Blood Counts',
  'Peripheral smear': 'Blood Counts',
  'Plasma Cell': 'Blood Counts',
  'Platelate Morphology': 'Blood Counts',
  'Platelet Count': 'Blood Counts',
  'Platelet Crit': 'Blood Counts',
  'Platelet(PBS)': 'Blood Counts',
  'Platelet-Lymphocyte Ratio': 'Blood Counts',
  'Platelets Morphology': 'Blood Counts',
  'Polymorphonuclear Leukocytes': 'Blood Counts',
  'Polymorphs': 'Blood Counts',
  'Pro-Myelocytes': 'Blood Counts',
  'Promonocytes': 'Blood Counts',
  'RBC Morphology': 'Blood Counts',
  'RBC count': 'Blood Counts',
  'RBC(PBS)': 'Blood Counts',
  'RBCs': 'Blood Counts',
  'RDW': 'Blood Counts',
  'RDW-CV': 'Blood Counts',
  'RDW-SD': 'Blood Counts',
  'RETICULOCYTE HEAMOGLOBIN EQUIVELENT': 'Blood Counts',
  'Reticulocyte Index': 'Blood Counts',
  'Reticulocytes Count': 'Blood Counts',
  'Segmented Neutrophils': 'Blood Counts',
  'Total Diff %': 'Blood Counts',
  'Total Leukocyte Count': 'Blood Counts',
  'WBC Morphology': 'Blood Counts',
  'WBC(PBS)': 'Blood Counts',

  // ── Blood Disorder ──
  'Activated Protein C Resistance (APCR)': 'Blood Disorder',
  'Band forms': 'Blood Disorder',
  'Clotting Time': 'Blood Disorder',
  'Coagulum': 'Blood Disorder',
  'Haemoglobin C (HbC)': 'Blood Disorder',
  'Haemoglobin D (HbD)': 'Blood Disorder',
  'Haemoglobin E (HbE)': 'Blood Disorder',
  'Haemoglobin S (HbS)': 'Blood Disorder',
  'Heparin Induced Thrombocytopenia (HIT)': 'Blood Disorder',
  'LUC - (Atypical cells)': 'Blood Disorder',
  'Parietal Cell Antibody': 'Blood Disorder',
  'Prolymphocytes': 'Blood Disorder',
  'VANCOMYCIN': 'Blood Disorder',

  // ── Blood Group ──
  'Blood Group': 'Blood Group',
  'Rh Factor': 'Blood Group',
  'Rh Factor Quantitative': 'Blood Group',

  // ── Bone Health ──
  'Alkaline Phosphatase with Bone Fraction Ostase': 'Bone Health',
  'Beta-2-Crosslaps C-Telopeptides (BCTX)': 'Bone Health',
  'Fibroblast Growth Factor 23 (FGF 23)': 'Bone Health',
  'NTx N-Tellopeptide, 24 Hrs Urine': 'Bone Health',
  'Osteocalcin': 'Bone Health',
  'Total P1NP': 'Bone Health',

  // ── COVID ──
  'COVID 19 IgM': 'COVID',
  'COVID Antibody': 'COVID',
  'COVID RT-PCR': 'COVID',
  'Covid-19 IgG': 'COVID',
  'Covid-19 IgG Antibody (Qualitative)': 'COVID',
  'Cycle Threshold E-gene': 'COVID',
  'Cycle Threshold N-gene': 'COVID',
  'Cycle Threshold Orf 1a-gene': 'COVID',
  'Cycle Threshold RDRP': 'COVID',

  // ── Cancer Profile ──
  '% fPSA': 'Cancer Profile',
  'Adrenaline (Epinephrine) level Urine': 'Cancer Profile',
  'Adrenaline (Epinephrine) level Urine 24 hrs': 'Cancer Profile',
  'BETA 2 MICROGLOBULIN': 'Cancer Profile',
  'CA 125': 'Cancer Profile',
  'CA 15-3': 'Cancer Profile',
  'CA 19-9': 'Cancer Profile',
  'CA 72.4 (TAG-72) GASTRIC CANCER MARKER,SERUM': 'Cancer Profile',
  'CEA': 'Cancer Profile',
  'CYFRA 21-1 (Lung Cancer Marker)': 'Cancer Profile',
  'Calcitonin': 'Cancer Profile',
  'Carcinoembryonic Antigen (CEA) Fluid': 'Cancer Profile',
  'Chromogranin A': 'Cancer Profile',
  'DES-GAMMA CARBOXY PROTHROMBIN (DCP)/PIVKA II': 'Cancer Profile',
  'HCG BETA, TOTAL, TUMOR MARKER': 'Cancer Profile',
  'HE4 (HUMAN EPIDIDYMIS PROTEIN 4) , SERUM': 'Cancer Profile',
  'HOMOVANILLIC ACID (HVA)': 'Cancer Profile',
  'Nor Metanephrine Free, Plasma': 'Cancer Profile',
  'Nor-Adrenaline (Nor-epinephrine) Plasma': 'Cancer Profile',
  'Prostate-Specific Antigen Free': 'Cancer Profile',
  'Prostate-Specific Antigen Total': 'Cancer Profile',
  'ROMA (Post-menopausal)': 'Cancer Profile',
  'ROMA (Pre-menopausal)': 'Cancer Profile',
  'Serotonin-(5-Hydroxy Tryptamine)': 'Cancer Profile',
  'TNF Alpha (Tumour Necrosis Factor)': 'Cancer Profile',
  'Tumor marker test': 'Cancer Profile',
  'p2PSA': 'Cancer Profile',
  'phi (Prostate Health Index)': 'Cancer Profile',

  // ── Cardiac Profile ──
  'BNP; B-TYPE NATRIURETIC PEPTIDE, PLASMA': 'Cardiac Profile',
  'CK-MB': 'Cardiac Profile',
  'CK-Total': 'Cardiac Profile',
  'Chylomicron Qualitative': 'Cardiac Profile',
  'Chylomicron Qualitative Urine': 'Cardiac Profile',
  'Homocysteine': 'Cardiac Profile',
  'Homocysteine Qualitative': 'Cardiac Profile',
  'LDH:Lactate Dehydrogenase': 'Cardiac Profile',
  'Lipoprotein Associated Phospholipase A2 (Lp-PLA2)': 'Cardiac Profile',
  'Myoglobin': 'Cardiac Profile',
  'Myoglobin, Serum': 'Cardiac Profile',
  'NT-Pro-BNP': 'Cardiac Profile',
  'TROPONI - I': 'Cardiac Profile',
  'TROPONIN-I,HIGH SENSITIVE': 'Cardiac Profile',
  'Troponin - T': 'Cardiac Profile',
  'Troponin I': 'Cardiac Profile',
  'Troponin-T High Sensitive': 'Cardiac Profile',

  // ── Covid ──
  'N Gene CT Value': 'Covid',

  // ── Diabetes Monitoring ──
  'Amylase': 'Diabetes Monitoring',
  'Anti GAD-65 Antibody (Paraneoplastic Syndrome)': 'Diabetes Monitoring',
  'Anti IA-2 (Insulinoma Associated Antigen)': 'Diabetes Monitoring',
  'Average Glucose Value(Past 3 Months IFCC)': 'Diabetes Monitoring',
  'Blood Glucose (1 Hour 30 Mins).': 'Diabetes Monitoring',
  'Blood Glucose (2 Hour 30 Mins)': 'Diabetes Monitoring',
  'Blood Glucose (30 MIns)': 'Diabetes Monitoring',
  'Blood Sugar (Fasting)': 'Diabetes Monitoring',
  'Blood Sugar (Postprandial)': 'Diabetes Monitoring',
  'Blood Sugar (Random)': 'Diabetes Monitoring',
  'C - PEPTIDE (Fasting)': 'Diabetes Monitoring',
  'C - PEPTIDE (PP)': 'Diabetes Monitoring',
  'C Peptide Random': 'Diabetes Monitoring',
  'Diabetes Monitoring': 'Diabetes Monitoring',
  'Fructosamine': 'Diabetes Monitoring',
  'Glucose (Fluid)': 'Diabetes Monitoring',
  'Glucose 2 Hour Post Load': 'Diabetes Monitoring',
  'Glucose Challenge Test (GCT)': 'Diabetes Monitoring',
  'Glycosylated Haemoglobin(Hb A1c) IFCC': 'Diabetes Monitoring',
  'HOMA IR Index': 'Diabetes Monitoring',
  'HbA1c (Glycosylated Haemoglobin)': 'Diabetes Monitoring',
  'HbA1c (mmol/mol)': 'Diabetes Monitoring',
  'Insulin (Fasting)': 'Diabetes Monitoring',
  'Insulin (Postprandial)': 'Diabetes Monitoring',
  'Insulin (Random)': 'Diabetes Monitoring',
  'KETONE BODY (BETA HYDROXYBUTYRATE)': 'Diabetes Monitoring',
  'Microalbumin': 'Diabetes Monitoring',
  'POST GLUCOSE (BLOOD SUGAR LEVELS)': 'Diabetes Monitoring',
  'Total Galactose (TGAL)~Galactosemia (GAL)': 'Diabetes Monitoring',
  'Urine Glucose (30 Mins)': 'Diabetes Monitoring',
  'Urine sugar(2hr)': 'Diabetes Monitoring',
  'Urine sugar(3hr)': 'Diabetes Monitoring',
  'ZnT8 (ZINC TRANSPORTER 8) ANTIBODY': 'Diabetes Monitoring',
  'eAG (Estimated Average Glucose)': 'Diabetes Monitoring',

  // ── Electrolyte Profile ──
  'Bicarbonate': 'Electrolyte Profile',
  'Calcium': 'Electrolyte Profile',
  'Calcium Ionised': 'Electrolyte Profile',
  'Calcium, Urine by Arsenazo III dye Method': 'Electrolyte Profile',
  'Chloride': 'Electrolyte Profile',
  'Chloride, Urine': 'Electrolyte Profile',
  'Corrected Calcium': 'Electrolyte Profile',
  'Lactate': 'Electrolyte Profile',
  'MANGANESE URINE': 'Electrolyte Profile',
  'Magnesium': 'Electrolyte Profile',
  'Magnesium,Serum': 'Electrolyte Profile',
  'Osmolality serum': 'Electrolyte Profile',
  'Phosphate': 'Electrolyte Profile',
  'Phosphates/Urates': 'Electrolyte Profile',
  'Phosphorus': 'Electrolyte Profile',
  'Phosphorus, Urine by Phosphomolybdate Method': 'Electrolyte Profile',
  'Potassium': 'Electrolyte Profile',
  'Potassium, Urine': 'Electrolyte Profile',
  'Potassium,Urine': 'Electrolyte Profile',
  'Selenium, Serum by ICPMS': 'Electrolyte Profile',
  'Serum Copper': 'Electrolyte Profile',
  'Sodium': 'Electrolyte Profile',
  'Sodium 24 Hours Total Volume': 'Electrolyte Profile',
  'Sodium : Potassium ratio': 'Electrolyte Profile',
  'Sodium urine by ISE Method': 'Electrolyte Profile',
  'Sodium,Urine': 'Electrolyte Profile',
  'Uric Acid': 'Electrolyte Profile',
  'Urinary Calcium level per day (Calculated)': 'Electrolyte Profile',
  'Urine Potassium per Day(Calculation)': 'Electrolyte Profile',
  'Urine Sodium Random': 'Electrolyte Profile',
  'Zinc': 'Electrolyte Profile',

  // ── Heart Assure ──
  'Heart Assure (High Sensitive Troponin I)': 'Heart Assure',

  // ── Hemoglobin Electrophoresis ──
  'HbA': 'Hemoglobin Electrophoresis',
  'HbA2': 'Hemoglobin Electrophoresis',
  'HbC': 'Hemoglobin Electrophoresis',
  'HbD': 'Hemoglobin Electrophoresis',
  'HbF': 'Hemoglobin Electrophoresis',
  'HbS': 'Hemoglobin Electrophoresis',
  'Unidentified': 'Hemoglobin Electrophoresis',

  // ── Hepatitis ──
  'Anti HCV': 'Hepatitis',
  'Anti Hbs Titre': 'Hepatitis',
  'CMV AB IgG': 'Hepatitis',
  'CMV AB IgM': 'Hepatitis',
  'HAV AB': 'Hepatitis',
  'HAV AB IgM': 'Hepatitis',
  'HAV AB Total': 'Hepatitis',
  'HBcAb IgM': 'Hepatitis',
  'HBcAb Total': 'Hepatitis',
  'HBeAg': 'Hepatitis',
  'HBsAb': 'Hepatitis',
  'HBsAg Test Value': 'Hepatitis',
  'HCV AB': 'Hepatitis',
  'HCV, IgG': 'Hepatitis',

  // ── Hormones ──
  '17-Hydroxy Progesterone': 'Hormones',
  '17-Hydroxy Progesterone (17-OHP)~Congenital Adrenal Hyperplasia (CAH)': 'Hormones',
  '17-HydroxyProgesterone': 'Hormones',
  'ADH (Anti Diuretic Hormone)': 'Hormones',
  'AMH': 'Hormones',
  'ANTI MULLERIAN HORMONE; AMH,SERUM': 'Hormones',
  'Aldosterone, Serum': 'Hormones',
  'Aldosterone, Urine': 'Hormones',
  'Alpha-fetoprotein (AFP)': 'Hormones',
  'Androstenedione': 'Hormones',
  'Beta HCG': 'Hormones',
  'Cortisol (Random)': 'Hormones',
  'Cortisol Serum (p.m)': 'Hormones',
  'Cortosol Random': 'Hormones',
  'DHEA-Sulphate': 'Hormones',
  'DHEAS': 'Hormones',
  'DHT': 'Hormones',
  'ESTRIOL, UNCONJUGATED / FREE (uE3), SERUM': 'Hormones',
  'Estradiol (E2)': 'Hormones',
  'Estrogen': 'Hormones',
  'FSH': 'Hormones',
  'Follicle Stimulating Hormone (FSH)': 'Hormones',
  'Free Androgen Index': 'Hormones',
  'Growth Hormone': 'Hormones',
  'HCG Beta Subunit, Urine Spot': 'Hormones',
  'IGF BP3': 'Hormones',
  'IGF-1 (Somatomedin C)': 'Hormones',
  'INHIBIN A, REPRODUCTIVE MARKER , SERUM': 'Hormones',
  'Inhibin': 'Hormones',
  'Inhibin A': 'Hormones',
  'LH / FSH Ratio': 'Hormones',
  'Leutinizing Harmone': 'Hormones',
  'Leutinizing Hormone': 'Hormones',
  'Oestradiol': 'Hormones',
  'PAPP-A (Pregnancy Associated Plasma Protein)': 'Hormones',
  'PAPPa (Pregnancy Associated Plasma Protein)': 'Hormones',
  'PlGF (Placental Growth Factor)': 'Hormones',
  'Placental growth factor (PlGF)': 'Hormones',
  'Pregnancy Associated Plasma Protein(PAPP-A)': 'Hormones',
  'Pregnancy Test Serum': 'Hormones',
  'Progesterone': 'Hormones',
  'Prolactin': 'Hormones',
  'SEX HORMONE BINDING GLOBULIN (SHBG),SERUM': 'Hormones',
  'SHBG': 'Hormones',
  'Serum for Beta HCG': 'Hormones',
  'TSH (Thyroid Stimulating Hormone)~Congenital Hypothyroidism (CH)': 'Hormones',
  'Testosterone': 'Hormones',
  'Testosterone(Free)': 'Hormones',
  'Urine for Beta HCG': 'Hormones',
  'uE3, unconjugated Estriol': 'Hormones',

  // ── Hypertension ──
  'Plasma Renin Direct': 'Hypertension',

  // ── Immunity ──
  'CD3': 'Immunity',
  'CD3-/CD(16+56)++': 'Immunity',
  'CD4': 'Immunity',
  'CD4/CD8 ratio': 'Immunity',
  'CD8': 'Immunity',
  'IMMUNOGLOBULIN IgA,Serum': 'Immunity',
  'IMMUNOGLOBULIN IgG,Serum': 'Immunity',
  'IMMUNOGLOBULIN IgM, SERUM': 'Immunity',
  'IgE Total': 'Immunity',
  'IgM Level': 'Immunity',
  'Natural Killer Cells': 'Immunity',

  // ── Infectious Diseases ──
  'ANTI HEV IgG': 'Infectious Diseases',
  'ASCA IgA': 'Infectious Diseases',
  'ASCA IgG': 'Infectious Diseases',
  'ASO Qualitative': 'Infectious Diseases',
  'Adenosine Deaminase; ADA': 'Infectious Diseases',
  'Adenovirus IgG': 'Infectious Diseases',
  'Adenovirus IgM Antibody': 'Infectious Diseases',
  'Agglutination': 'Infectious Diseases',
  'Anti-HBc IgM': 'Infectious Diseases',
  'Anti-HBe': 'Infectious Diseases',
  'Anti-HBs': 'Infectious Diseases',
  'Anti-HCV': 'Infectious Diseases',
  'Anti-HDV': 'Infectious Diseases',
  'Antistreptolysin-O ( ASO) Titre, Serum': 'Infectious Diseases',
  'Aspergillus Antigen': 'Infectious Diseases',
  'Beta-D-Glucan': 'Infectious Diseases',
  'CMV IgG': 'Infectious Diseases',
  'CMV IgM': 'Infectious Diseases',
  'Chikungunya IgG': 'Infectious Diseases',
  'Chikungunya IgM': 'Infectious Diseases',
  'Chlamydia IgA': 'Infectious Diseases',
  'Chlamydia IgG': 'Infectious Diseases',
  'Chlamydia Trachomatis IgG': 'Infectious Diseases',
  'Coxiella IgG': 'Infectious Diseases',
  'Coxiella IgM': 'Infectious Diseases',
  'Coxsackie IgG Antibody': 'Infectious Diseases',
  'Coxsackie IgM Antibody': 'Infectious Diseases',
  'Cryptococcus Antigen': 'Infectious Diseases',
  'Cryptosporidium Antigen': 'Infectious Diseases',
  'Cyst (Stool routine)': 'Infectious Diseases',
  'Cytomegalovirus Antibody-IgM': 'Infectious Diseases',
  'Diphtheria Antibogy IgG': 'Infectious Diseases',
  'Direct Microscopy (Saline and Iodine mount)': 'Infectious Diseases',
  'E Gene CT Value': 'Infectious Diseases',
  'E. Coli Antigen': 'Infectious Diseases',
  'EBV EA IgG': 'Infectious Diseases',
  'EBV IgM': 'Infectious Diseases',
  'Echinococcus IgG': 'Infectious Diseases',
  'Entamoeba Antigen': 'Infectious Diseases',
  'Epstein-Barr VCA IgG': 'Infectious Diseases',
  'Estimated Titre': 'Infectious Diseases',
  'Factor V Functional / Activity': 'Infectious Diseases',
  'Filaria Antigen': 'Infectious Diseases',
  'Filaria IgG': 'Infectious Diseases',
  'Filaria IgM': 'Infectious Diseases',
  'Form & Consistency  (Stool routine)': 'Infectious Diseases',
  'Giardia Antigen': 'Infectious Diseases',
  'Group B Strep': 'Infectious Diseases',
  'H. Influenzae B': 'Infectious Diseases',
  'HAV IgM': 'Infectious Diseases',
  'HCV Total': 'Infectious Diseases',
  'HDV IgM': 'Infectious Diseases',
  'HEPATITIS B CORE ANTIBODY (Anti- HBc), TOTAL': 'Infectious Diseases',
  'HEV IgM': 'Infectious Diseases',
  'HIV 1&2': 'Infectious Diseases',
  'HMPV RNA Qualitative': 'Infectious Diseases',
  'HSV 1&2 IgM': 'Infectious Diseases',
  'HSV-1 IgG': 'Infectious Diseases',
  'HSV-2 IgG': 'Infectious Diseases',
  'HTLV I & II Total Antibody': 'Infectious Diseases',
  'Hepatitis A  Antibody (Anti-HAV)- IgG': 'Infectious Diseases',
  'Hepatitis B Envelope Antigen (HBeAg )': 'Infectious Diseases',
  'Hepatitis B surface antigen (HBs Ag)': 'Infectious Diseases',
  'Herpes simplex virus 1+2, IgG': 'Infectious Diseases',
  'Herpes simplex virus 1+2, IgM': 'Infectious Diseases',
  'Induration in mm': 'Infectious Diseases',
  'Influenza A IgG': 'Infectious Diseases',
  'Influenza B IgM': 'Infectious Diseases',
  'Influenza IgG': 'Infectious Diseases',
  'LEPTOSPIRA ANTIBODY, IgM,SERUM': 'Infectious Diseases',
  'LEPTOSPIRA ANTIBODY,IgG,RAPID CARD': 'Infectious Diseases',
  'LEPTOSPIRA ANTIBODY,IgM,RAPID CARD': 'Infectious Diseases',
  'Legionella Antigen': 'Infectious Diseases',
  'Legionella IgG': 'Infectious Diseases',
  'Legionella IgM': 'Infectious Diseases',
  'Leishmania IgG': 'Infectious Diseases',
  'Leptospira IgG': 'Infectious Diseases',
  'Lyme IgG': 'Infectious Diseases',
  'LymeBorrelia Burgdorferi IgM antibodies': 'Infectious Diseases',
  'Measles IgG': 'Infectious Diseases',
  'Measles IgM': 'Infectious Diseases',
  'Monospot': 'Infectious Diseases',
  'Mumps IgG': 'Infectious Diseases',
  'Mumps IgM': 'Infectious Diseases',
  'Mycobacterium tuberculosis complex (MTBC)': 'Infectious Diseases',
  'Mycoplasma Pneumoniae IgG': 'Infectious Diseases',
  'Ova (Stool routine)': 'Infectious Diseases',
  'Parvovirus (B19) IgM*': 'Infectious Diseases',
  'Pertussis IgG': 'Infectious Diseases',
  'Pneumococcal Antigen': 'Infectious Diseases',
  'Post Stool Concentration Microscopy (Saline and Iodine mount)': 'Infectious Diseases',
  'ROTAVIRUS ANTIGEN, STOOL': 'Infectious Diseases',
  'RPR, Serum': 'Infectious Diseases',
  'RSV IgG': 'Infectious Diseases',
  'RSV IgM': 'Infectious Diseases',
  'Rabies antibody IgG': 'Infectious Diseases',
  'RdRp Gene CT Value': 'Infectious Diseases',
  'Rubella Ab IgG': 'Infectious Diseases',
  'Rubella Ab IgM': 'Infectious Diseases',
  'SARS CoV-2 RNA Qualitative': 'Infectious Diseases',
  'SARS-CoV-2 IgG': 'Infectious Diseases',
  'SCRUB TYPHUS (TSUTSUGAMUSHI) ANTIBODY IgM, RAPID ASSAY': 'Infectious Diseases',
  'Salmonella Antigen': 'Infectious Diseases',
  'Salmonella H': 'Infectious Diseases',
  'Salmonella IgG': 'Infectious Diseases',
  'Salmonella IgM': 'Infectious Diseases',
  'Salmonella O': 'Infectious Diseases',
  'Salmonella Paratyphi B(H)': 'Infectious Diseases',
  'Salmonella paratyphi A(H)': 'Infectious Diseases',
  'Scrub Typhus IgG': 'Infectious Diseases',
  'Scrub Typhus IgM': 'Infectious Diseases',
  'Syphilis Antibodies': 'Infectious Diseases',
  'TB Antigen': 'Infectious Diseases',
  'TB Antigen-Nil': 'Infectious Diseases',
  'TB Nil': 'Infectious Diseases',
  'TB Resistance': 'Infectious Diseases',
  'TPHA': 'Infectious Diseases',
  'Tetanus IgG': 'Infectious Diseases',
  'Titre': 'Infectious Diseases',
  'Toxoplasma Ab IgG': 'Infectious Diseases',
  'Toxoplasma Ab IgM': 'Infectious Diseases',
  'Treponema Pallidium Haemagglutination (TPHA) TITRE': 'Infectious Diseases',
  'Trophozoites (Stool routine)': 'Infectious Diseases',
  'Tuberculin Test': 'Infectious Diseases',
  'West Nile IgG': 'Infectious Diseases',
  'West Nile IgM': 'Infectious Diseases',
  'Worms (Adult/Segment) (Stool routine)': 'Infectious Diseases',
  'ZN Stain': 'Infectious Diseases',
  'p24 antigen with HIV 1 & 2 Antibody': 'Infectious Diseases',

  // ── Inflammation ──
  'Amyloid A': 'Inflammation',
  'C-reactive protein (CRP),Qualitative': 'Inflammation',
  'CRP': 'Inflammation',
  'Fibrinogen level': 'Inflammation',
  'IL6': 'Inflammation',
  'Mucus  (Stool routine)': 'Inflammation',
  'WBC count (Synovial Fluid)': 'Inflammation',

  // ── Kidney Profile ──
  '17 Ketosteroids,urine': 'Kidney Profile',
  '24 Hours Total Volume(Urine)': 'Kidney Profile',
  '24 Hrs total volume': 'Kidney Profile',
  'ALBUMIN, FLUID': 'Kidney Profile',
  'Albumin Qualitative, Urine': 'Kidney Profile',
  'Albuminuria': 'Kidney Profile',
  'Aminolevulinic acid 24Hrs Urine': 'Kidney Profile',
  'BUN : Creatinine ratio': 'Kidney Profile',
  'Blood Urea': 'Kidney Profile',
  'Blood Urea Nitrogen (BUN)': 'Kidney Profile',
  'Calcium, Urine,': 'Kidney Profile',
  'Creatinine Clearence (Calculated)': 'Kidney Profile',
  'Creatinine Urine per day(Calculated)': 'Kidney Profile',
  'Creatinine, 24 hours urine (Calculated)': 'Kidney Profile',
  'Creatinine, Fluid': 'Kidney Profile',
  'Creatinine, Urine by Jaffe Method': 'Kidney Profile',
  'Cystatin C': 'Kidney Profile',
  'Cystine Quantitative, Spot Urine': 'Kidney Profile',
  'Glomerular Filtration Rate': 'Kidney Profile',
  'Glomerular Filtration Rate CKD': 'Kidney Profile',
  'Microalb / Creatinine Ratio': 'Kidney Profile',
  'Microalbumin : Creatinine ratio': 'Kidney Profile',
  'Microalbumin, Urine per day': 'Kidney Profile',
  'Nor-Epinephrine, 24 Hrs Urine': 'Kidney Profile',
  'Osmolality urine': 'Kidney Profile',
  'Oxalate, Urine': 'Kidney Profile',
  'Protein,urine 24 hours': 'Kidney Profile',
  'SERUM BICARBONATE(D)': 'Kidney Profile',
  'Serum Creatinine': 'Kidney Profile',
  'Sodium urine per day (Calculated)': 'Kidney Profile',
  'Total Proteins (Fluid, Biochemical)': 'Kidney Profile',
  'Total urine volume in 24 hrs': 'Kidney Profile',
  'Urea : Creatinine ratio': 'Kidney Profile',
  'Urinary Phosphorus level per day (Calculated)': 'Kidney Profile',
  'Urine volume in 24 hours': 'Kidney Profile',
  'Urine volume in 24 hours.': 'Kidney Profile',

  // ── Lipid Profile ──
  'APO A : APO B Ratio': 'Lipid Profile',
  'APO B : APO A Ratio': 'Lipid Profile',
  'Apo A': 'Lipid Profile',
  'Apo B': 'Lipid Profile',
  'Bile Acid (Fasting)': 'Lipid Profile',
  'Bile Acid (Postprandial)': 'Lipid Profile',
  'Direct LDL Cholestrol': 'Lipid Profile',
  'HDL % of total': 'Lipid Profile',
  'HDL : LDL ratio': 'Lipid Profile',
  'HDL :Total Cholesterol ratio': 'Lipid Profile',
  'HDL Cholesterol': 'Lipid Profile',
  'HsCRP': 'Lipid Profile',
  'LDL : HDL ratio': 'Lipid Profile',
  'LDL Cholesterol': 'Lipid Profile',
  'Lipoprotein (a) [Lp(a)]': 'Lipid Profile',
  'Non - HDL Cholesterol': 'Lipid Profile',
  'TG : HDL Ratio': 'Lipid Profile',
  'TOTAL LIPID': 'Lipid Profile',
  'Total Cholesterol': 'Lipid Profile',
  'Total Cholesterol : HDL ratio': 'Lipid Profile',
  'Triglycerides': 'Lipid Profile',
  'VLDL': 'Lipid Profile',

  // ── Liver Profile ──
  'ALP': 'Liver Profile',
  'ALP - GGT RATIO': 'Liver Profile',
  'AST / ALT Ratio': 'Liver Profile',
  'Albumin': 'Liver Profile',
  'Albumin / Creatinine ratio': 'Liver Profile',
  'Albumin : Globulin ratio': 'Liver Profile',
  'Alpha 2 Macroglobulin': 'Liver Profile',
  'Alpha Feto Protein (AFP),Serum': 'Liver Profile',
  'Bile Acids-Total': 'Liver Profile',
  'Bilirubin Total (Fluid)': 'Liver Profile',
  'Creatine-Kinase': 'Liver Profile',
  'Direct Bilirubin': 'Liver Profile',
  'FIB-4 Score': 'Liver Profile',
  'Fatty liver Index(FLI)': 'Liver Profile',
  'GGT': 'Liver Profile',
  'Globulin': 'Liver Profile',
  'Indirect Bilirubin': 'Liver Profile',
  'LDH': 'Liver Profile',
  'NAFLD Fibrosis score': 'Liver Profile',
  'Pre Albumin': 'Liver Profile',
  'Protein (Total)': 'Liver Profile',
  'Pseudocholinesterase,Serum': 'Liver Profile',
  'SGOT (ALT)': 'Liver Profile',
  'SGOT (AST)': 'Liver Profile',
  'SGPT (ALT)': 'Liver Profile',
  'SGPT (AST)': 'Liver Profile',
  'Total Bilirubin': 'Liver Profile',

  // ── Malaria Profile ──
  'Malaria Parasite': 'Malaria Profile',

  // ── Mineral Profile ──
  'ALUMINUM, SERUM': 'Mineral Profile',
  'Aluminum spot urine': 'Mineral Profile',
  'CADMIUM': 'Mineral Profile',
  'Cobalt Blood': 'Mineral Profile',
  'Copper': 'Mineral Profile',
  'Manganese ICPMS': 'Mineral Profile',
  'Phosphorus, Spot Urine': 'Mineral Profile',
  'Thallium - Blood': 'Mineral Profile',
  'Thallium ICPMS Urine Spot': 'Mineral Profile',
  'Zinc Urine by ICPMS': 'Mineral Profile',

  // ── Neurological Disorders ──
  'ACTH, EDTA PLASMA': 'Neurological Disorders',
  'AChR- Acetyl Choline Receptor Antibodies': 'Neurological Disorders',
  'AMPA (Anti-glutamate receptor)-GluR1': 'Neurological Disorders',
  'AMPA (Anti-glutamate receptor)-GluR2': 'Neurological Disorders',
  'ANNA-1/Hu': 'Neurological Disorders',
  'ANNA-2/Ri': 'Neurological Disorders',
  'ASKA (Striated) Muscle Antibody': 'Neurological Disorders',
  'Albumin CSF': 'Neurological Disorders',
  'Amphiphysin': 'Neurological Disorders',
  'Amphiphysin Antibody': 'Neurological Disorders',
  'Angiotensin Converting Enzyme (ACE) CSF': 'Neurological Disorders',
  'Anti Hu Antibody': 'Neurological Disorders',
  'Anti Myelin Oligodendrocyte Glycoprotein (MOG)': 'Neurological Disorders',
  'Anti Neuromyelitis Optica / Aquaporin 4 (NMO)': 'Neurological Disorders',
  'Anti Phospholipase A2 Recepto': 'Neurological Disorders',
  'CASPR2 antibody (VGKC type)': 'Neurological Disorders',
  'CSF Glucose': 'Neurological Disorders',
  'CSF Proteins': 'Neurological Disorders',
  'CV2.1': 'Neurological Disorders',
  'Carbamazepine (Tegretol)': 'Neurological Disorders',
  'Cryptococcus Antigen, CSF': 'Neurological Disorders',
  'GABA-B receptor antibody': 'Neurological Disorders',
  'GD1a': 'Neurological Disorders',
  'GD1b': 'Neurological Disorders',
  'GM1': 'Neurological Disorders',
  'GM2': 'Neurological Disorders',
  'GM3': 'Neurological Disorders',
  'GQ1b': 'Neurological Disorders',
  'GT1b': 'Neurological Disorders',
  'Immunoglobulin G (IgG), CSF': 'Neurological Disorders',
  'Japanese Encephalitis Virus By PCR': 'Neurological Disorders',
  'Japanese Encephalitis Virus IgM Antibody': 'Neurological Disorders',
  'LGI-1 antibody (VGKC type)': 'Neurological Disorders',
  'Lactate CSF': 'Neurological Disorders',
  'Levetiracetam': 'Neurological Disorders',
  'M2-3E (BPO) Antibody': 'Neurological Disorders',
  'MuSK ANTIBODY': 'Neurological Disorders',
  'Myelin Associated Glycoprotein (MAG)': 'Neurological Disorders',
  'NMDA (Anti-glutamate receptor against NR1 subunit)': 'Neurological Disorders',
  'Neuron Specific Enolase (NSE)': 'Neurological Disorders',
  'PCA-1/Yo': 'Neurological Disorders',
  'PHENYTOIN, SERUM': 'Neurological Disorders',
  'PNMA2 (Ma2/Ta)': 'Neurological Disorders',
  'Phenobarbitone (Gardinal)': 'Neurological Disorders',
  'Protein Total CSF': 'Neurological Disorders',
  'VALPROIC ACID, SERUM': 'Neurological Disorders',
  'VDRL CSF': 'Neurological Disorders',
  'Yo Antibody': 'Neurological Disorders',

  // ── Pancreas ──
  'Amylase, Fluid': 'Pancreas',
  'Canine Pancreatic Lipase Immunoreactivity': 'Pancreas',
  'Feline Pancreatic Lipase Immunoreactivity': 'Pancreas',
  'Lipase': 'Pancreas',
  'Lipase Fluid': 'Pancreas',
  'Trypsin-Like Immunoractivity': 'Pancreas',

  // ── Prothrombin Time ──
  'Mean Normal Prothrombic Time': 'Prothrombin Time',
  'PT (Control)': 'Prothrombin Time',
  'PT ratio': 'Prothrombin Time',
  'PT-INR': 'Prothrombin Time',
  'Partial Thromboplastin Time(Control)': 'Prothrombin Time',

  // ── STD Profile ──
  'Chlamydia IgM': 'STD Profile',
  'Gonorrhoea Ag': 'STD Profile',
  'HBsAg': 'STD Profile',
  'HCV': 'STD Profile',
  'HIV': 'STD Profile',
  'HIV AB': 'STD Profile',
  'HIV Combo (Ag+Ab)': 'STD Profile',
  'HPV': 'STD Profile',
  'Hepatitis B': 'STD Profile',
  'Herpes Semplex Virus': 'STD Profile',
  'Herpes Semplex Virus I IgM': 'STD Profile',
  'Herpes Semplex Virus II IgM': 'STD Profile',
  'High Vaginal Swab': 'STD Profile',
  'RAPID TP(SYPHILIS), VDRL': 'STD Profile',
  'Rapid Plasma Reagin': 'STD Profile',
  'TPHA (TREPONEMA PALLIDUM)': 'STD Profile',
  'VDRL': 'STD Profile',

  // ── Semen Analysis ──
  'Abnormal Form': 'Semen Analysis',
  'Abnormal Forms': 'Semen Analysis',
  'Abnormal Head': 'Semen Analysis',
  'Abnormal Neck 8 midpiece': 'Semen Analysis',
  'Abnormal Tail': 'Semen Analysis',
  'Abstinence Period': 'Semen Analysis',
  'Alive Spermatozoa %': 'Semen Analysis',
  'Analysis Time': 'Semen Analysis',
  'Appearance (Semen)': 'Semen Analysis',
  'Appearance of Semen': 'Semen Analysis',
  'Collection Time': 'Semen Analysis',
  'Days Of Abstinence': 'Semen Analysis',
  'Dead Spermatozoa %': 'Semen Analysis',
  'Immotile': 'Semen Analysis',
  'Immotile (IM %)': 'Semen Analysis',
  'Leukocyte (Semen)': 'Semen Analysis',
  'Liquefaction': 'Semen Analysis',
  'Liquefaction Time (Semen)': 'Semen Analysis',
  'Microscopic Examination (Microscopy) Vitality': 'Semen Analysis',
  'Morphology Abnormal': 'Semen Analysis',
  'Morphology Head Defects': 'Semen Analysis',
  'Morphology Mid Picce Defects': 'Semen Analysis',
  'Morphology Normal': 'Semen Analysis',
  'Morphology Tail Defects': 'Semen Analysis',
  'Motile': 'Semen Analysis',
  'Motility Assessment(After Liquefaction)': 'Semen Analysis',
  'Non Progressive': 'Semen Analysis',
  'Non Progressive (NP, %)': 'Semen Analysis',
  'Normal Form': 'Semen Analysis',
  'Progressive': 'Semen Analysis',
  'Progressive (PR, %)': 'Semen Analysis',
  'Semen Fructose': 'Semen Analysis',
  'Sperm Antibody (ASAB) -Total': 'Semen Analysis',
  'Sperm Count / ejaculate': 'Semen Analysis',
  'Sperm Count / ml': 'Semen Analysis',
  'Total Motility (PR+NP, %)': 'Semen Analysis',
  'Volume of Semen': 'Semen Analysis',
  'WBCs': 'Semen Analysis',
  'pH of Semen': 'Semen Analysis',

  // ── Semen Culture and Sensitivity ──
  'Amikacin': 'Semen Culture and Sensitivity',
  'Amoxycillin': 'Semen Culture and Sensitivity',
  'Amoxycillin + Clavulanic Acid': 'Semen Culture and Sensitivity',
  'Ampicillin': 'Semen Culture and Sensitivity',
  'Ampicillin + Salbactum': 'Semen Culture and Sensitivity',
  'Aztreonam': 'Semen Culture and Sensitivity',
  'Cefazolin': 'Semen Culture and Sensitivity',
  'Cefepime': 'Semen Culture and Sensitivity',
  'Cefitriaxone': 'Semen Culture and Sensitivity',
  'Cefoperazone + Sulbactum': 'Semen Culture and Sensitivity',
  'Cefotaxime': 'Semen Culture and Sensitivity',
  'Cefoxitin': 'Semen Culture and Sensitivity',
  'Ceftazidime': 'Semen Culture and Sensitivity',
  'Cefuroxime': 'Semen Culture and Sensitivity',
  'Ciprofloxacin': 'Semen Culture and Sensitivity',
  'Cotrimoxazole': 'Semen Culture and Sensitivity',
  'Gentamicin': 'Semen Culture and Sensitivity',
  'Imipenem': 'Semen Culture and Sensitivity',
  'Levofloxacine': 'Semen Culture and Sensitivity',
  'Meropenem': 'Semen Culture and Sensitivity',
  'Norfloxacin': 'Semen Culture and Sensitivity',
  'Oflaxacine': 'Semen Culture and Sensitivity',
  'Piperacillin': 'Semen Culture and Sensitivity',
  'Piperacillin + Tazobactum': 'Semen Culture and Sensitivity',
  'Primary Smear of Semen': 'Semen Culture and Sensitivity',
  'Semen Type': 'Semen Culture and Sensitivity',
  'Tetracycline': 'Semen Culture and Sensitivity',
  'Ticarcillin': 'Semen Culture and Sensitivity',
  'Ticarcillin + Clavulanic Acid': 'Semen Culture and Sensitivity',

  // ── Stool Analysis ──
  'Adult Parasite': 'Stool Analysis',
  'Blood (Stool routine)': 'Stool Analysis',
  'Cysts': 'Stool Analysis',
  'Epithelial Cells (Stool routine)': 'Stool Analysis',
  'Fat (Stool routine)': 'Stool Analysis',
  'OVA': 'Stool Analysis',
  'Occult Blood in Stool': 'Stool Analysis',
  'Organism Isolated': 'Stool Analysis',
  'Pus Cells (WBCs) (Stool routine)': 'Stool Analysis',
  'Pus Cells in Stool': 'Stool Analysis',
  'Reaction (Stool routine)': 'Stool Analysis',
  'Red Blood Cell': 'Stool Analysis',
  'Red blood Cells (Stool routine)': 'Stool Analysis',
  'Stool Color': 'Stool Analysis',
  'Stool Consistency': 'Stool Analysis',
  'Stool Mucus': 'Stool Analysis',
  'Stool Odour': 'Stool Analysis',
  'Stool Specimen Type': 'Stool Analysis',
  'Trophozoites': 'Stool Analysis',
  'Undigested Food': 'Stool Analysis',
  'Undigestive Material (Stool routine)': 'Stool Analysis',
  'Visible Blood': 'Stool Analysis',

  // ── Thyroid Profile ──
  'AMA- M2': 'Thyroid Profile',
  'ANTI THYROID PEROXIDASE ANTIBODY;(ANTI TPO), SERUM': 'Thyroid Profile',
  'Anti Thyroglobulin Abs': 'Thyroid Profile',
  'Antimitochondrial M2 Antibody': 'Thyroid Profile',
  'Free T3 (Triiodothyronine)': 'Thyroid Profile',
  'Free T4 (Thyroxine)': 'Thyroid Profile',
  'Microsomal (TPO) Antibody': 'Thyroid Profile',
  'Mitochondrial (M2) Antibody': 'Thyroid Profile',
  'Parathyroid Hormone (PTH)': 'Thyroid Profile',
  'T3 (Triiodothyronine)': 'Thyroid Profile',
  'T4 (Thyroxine)': 'Thyroid Profile',
  'THYROGLOBULIN': 'Thyroid Profile',
  'TSH': 'Thyroid Profile',
  'TSH 3RD GENERATION': 'Thyroid Profile',
  'TSH RECEPTOR ANTIBODY, SERUM': 'Thyroid Profile',
  'Thyroxine Binding Globulin (TBG)': 'Thyroid Profile',
  'Ultra TSH': 'Thyroid Profile',

  // ── Toxic elements ──
  'Aluminium': 'Toxic elements',
  'Antimony': 'Toxic elements',
  'Arsenic': 'Toxic elements',
  'Arsenic in 24 hrs Urine': 'Toxic elements',
  'Arsenic, Urine': 'Toxic elements',
  'Barium': 'Toxic elements',
  'Beryllium': 'Toxic elements',
  'Bismuth': 'Toxic elements',
  'Cadmium': 'Toxic elements',
  'Caesium': 'Toxic elements',
  'Chromium': 'Toxic elements',
  'Cobalt': 'Toxic elements',
  'Copper, Urine Spot': 'Toxic elements',
  'Lead': 'Toxic elements',
  'Lead Urine Spot by ICPMS': 'Toxic elements',
  'Lead, Blood': 'Toxic elements',
  'METHADONE SCREEN, URINE': 'Toxic elements',
  'METHAMPHETAMINE SCREEN, URINE': 'Toxic elements',
  'Manganese': 'Toxic elements',
  'Mercury': 'Toxic elements',
  'Mercury Serum by ICPMS': 'Toxic elements',
  'Molybdenum': 'Toxic elements',
  'Nickel': 'Toxic elements',
  'Nickel Serum': 'Toxic elements',
  'Nicotine - Cotinine Urine': 'Toxic elements',
  'Nicotine Metabolite, Urine': 'Toxic elements',
  'Phenol Urine': 'Toxic elements',
  'Selenium': 'Toxic elements',
  'Silver': 'Toxic elements',
  'Strontium': 'Toxic elements',
  'Thallium': 'Toxic elements',
  'Tin': 'Toxic elements',
  'Uranium': 'Toxic elements',
  'Vanadium': 'Toxic elements',

  // ── Tumour Marker Test ──
  'Alfa Feto Protein (AFP)': 'Tumour Marker Test',

  // ── Urinalysis ──
  'Absorbic Acid': 'Urinalysis',
  'Acetone': 'Urinalysis',
  'Albumin, Urine': 'Urinalysis',
  'Amorphous Deposit': 'Urinalysis',
  'Appearance': 'Urinalysis',
  'Bacteria': 'Urinalysis',
  'Bile Pigment': 'Urinalysis',
  'Bile Salts': 'Urinalysis',
  'Bilirubin': 'Urinalysis',
  'Blood': 'Urinalysis',
  'Candida in Urine': 'Urinalysis',
  'Casts': 'Urinalysis',
  'Chemical Examination': 'Urinalysis',
  'Crystals': 'Urinalysis',
  'DEPOSITS :': 'Urinalysis',
  'Epithelial Cells': 'Urinalysis',
  'Frank blood': 'Urinalysis',
  'Glucose in Urine': 'Urinalysis',
  'Ketone': 'Urinalysis',
  'Ketones in Urine': 'Urinalysis',
  'Leukocyte Esterase': 'Urinalysis',
  'Leukocyte esterase': 'Urinalysis',
  'Leukocytes': 'Urinalysis',
  'Microorganism': 'Urinalysis',
  'Microscopic Examination': 'Urinalysis',
  'Nitrite': 'Urinalysis',
  'Other compounds in Urine': 'Urinalysis',
  'Protein': 'Urinalysis',
  'Protein urine': 'Urinalysis',
  'Protozoa': 'Urinalysis',
  'Pus Cells': 'Urinalysis',
  'RBC': 'Urinalysis',
  'Reducing Substances': 'Urinalysis',
  'SPOT PROTEIN & CREATININE RATIO': 'Urinalysis',
  'Sediment': 'Urinalysis',
  'Specific Gravity': 'Urinalysis',
  'Sugar in Urine': 'Urinalysis',
  'Trichomonas Vaginalis': 'Urinalysis',
  'URINE SPOT CREATININE': 'Urinalysis',
  'URINE SPOT PROTEIN': 'Urinalysis',
  'Urinary Albumin': 'Urinalysis',
  'Urinary Calcium': 'Urinalysis',
  'Urinary Creatinine': 'Urinalysis',
  'Urinary Sodium': 'Urinalysis',
  'Urine Clarity': 'Urinalysis',
  'Urine Colour': 'Urinalysis',
  'Urine Ketones (1 Hour 30 Mins)': 'Urinalysis',
  'Urine Ketones (2 Hour)': 'Urinalysis',
  'Urine Ketones (30 Mins)': 'Urinalysis',
  'Urine Odour': 'Urinalysis',
  'Urine Spot Microalbumin': 'Urinalysis',
  'Urobilinogen': 'Urinalysis',
  'VOLUME': 'Urinalysis',
  'Yeast cells': 'Urinalysis',
  'pH': 'Urinalysis',

  // ── Viral Infections ──
  'Dengue IgG': 'Viral Infections',
  'Dengue IgM': 'Viral Infections',
  'Dengue NS1': 'Viral Infections',
  'Malaria (FALCIPARUM)': 'Viral Infections',
  'Malaria (VIVAX)': 'Viral Infections',
  'S.Typhi AH': 'Viral Infections',
  'S.Typhi BH': 'Viral Infections',
  'S.Typhi H Antibody': 'Viral Infections',
  'S.Typhi O Antibody': 'Viral Infections',
  'Typhoid (Widal Test)': 'Viral Infections',
  'Varicella Zoster Ab IgG': 'Viral Infections',

  // ── Vitamin Profile ──
  '1,25-Dihydroxy vitamin D': 'Vitamin Profile',
  'Biotin': 'Vitamin Profile',
  'Ceruloplasmin': 'Vitamin Profile',
  'Fat Burner': 'Vitamin Profile',
  'Folate (Folic Acid) *': 'Vitamin Profile',
  'Glutathione': 'Vitamin Profile',
  'Holotranscobalamin (Active Vitamin B12)': 'Vitamin Profile',
  'Vitamin A': 'Vitamin Profile',
  'Vitamin B-Complex': 'Vitamin Profile',
  'Vitamin B1': 'Vitamin Profile',
  'Vitamin B12': 'Vitamin Profile',
  'Vitamin B2': 'Vitamin Profile',
  'Vitamin B3': 'Vitamin Profile',
  'Vitamin B3 (Niacin)': 'Vitamin Profile',
  'Vitamin B6': 'Vitamin Profile',
  'Vitamin B7 (BIOTIN)': 'Vitamin Profile',
  'Vitamin B9': 'Vitamin Profile',
  'Vitamin C': 'Vitamin Profile',
  'Vitamin D (25-Hydroxy)': 'Vitamin Profile',
  'Vitamin E': 'Vitamin Profile',
  'Vitamin K1 (Phylloquinone)': 'Vitamin Profile',
};
