/**
 * InDepth — How to Read This Report Page
 *
 * Static explainer page that teaches the patient how to interpret
 * the report's visual language:
 *   - What the overall score means
 *   - What the severity badges mean (stable / monitor / critical)
 *   - How to read the speedometer
 *   - How to read the range slider
 *   - What "abnormal" means
 *
 * This page does NOT depend on the report data — it is static content
 * driven only by strategy flags (premium pages include more detail).
 *
 * Receives: NormalizedReport (for patient header only)
 */

import type { ReportPage, PageRenderContext } from '../../core/page-registry/page.types';
import type { NormalizedReport } from '../../domain/models/report.model';

/* ------------------------------------------------------------------ */

interface ExplainerItem {
    icon: string;
    title: string;
    body: string;
}

const EXPLAINER_ITEMS: ExplainerItem[] = [
    {
        icon: '🎯',
        title: 'Overall Health Score',
        body: 'A number from 0 to 100 that summarises all your test results into one metric. '
            + '<strong>70–100</strong> is healthy, <strong>40–69</strong> needs monitoring, '
            + 'and <strong>below 40</strong> requires prompt attention.',
    },
    {
        icon: '🟢',
        title: 'Severity Badges',
        body: '<strong style="color:#2E7D32">STABLE</strong> — All parameters within healthy range. '
            + '<strong style="color:#F9A825">MONITOR</strong> — One or more parameters are slightly out of range; '
            + 'discuss with your doctor. '
            + '<strong style="color:#C62828">CRITICAL</strong> — One or more parameters require immediate clinical attention.',
    },
    {
        icon: '🌡️',
        title: 'The Speedometer (Gauge)',
        body: 'The dial shows where your result sits across three zones: '
            + '<em style="color:#C62828">Red</em> (low / attention), '
            + '<em style="color:#F9A825">Amber</em> (borderline / monitor), and '
            + '<em style="color:#2E7D32">Green</em> (healthy / normal). '
            + 'The needle points to your score.',
    },
    {
        icon: '📏',
        title: 'Range Sliders',
        body: 'A horizontal bar showing the reference range (normal zone) and where your value falls. '
            + 'A dot marker outside the green zone indicates an abnormal result.',
    },
    {
        icon: '⚠️',
        title: 'Abnormal Parameters',
        body: 'A parameter is flagged as <em>high</em>, <em>low</em>, or <em>critical</em> when it falls '
            + 'outside the reference range for your age and gender. '
            + 'Always discuss abnormal results with a qualified healthcare provider.',
    },
    {
        icon: '📋',
        title: 'Profile Sections',
        body: 'Results are grouped by body system (e.g. Lipid Profile, Thyroid, Blood Sugar). '
            + 'Each section has its own score and severity badge so you can quickly see which system needs attention.',
    },
];

function renderExplainerCard(item: ExplainerItem): string {
    return `
<div class="htr-card">
  <div class="htr-card__icon">${item.icon}</div>
  <div class="htr-card__body">
    <div class="htr-card__title">${item.title}</div>
    <div class="htr-card__text">${item.body}</div>
  </div>
</div>`;
}

/* ------------------------------------------------------------------ */

export const inDepthHowToReadPage: ReportPage = {
    name: 'indepth-how-to-read',

    generate(ctx: PageRenderContext): string {
        const report = ctx.data as NormalizedReport;
        void report; // not used — static content only

        const cards = EXPLAINER_ITEMS.map(renderExplainerCard).join('\n');

        return `
<section class="indepth-how-to-read">
  <h1 class="htr-title">How to Read This Report</h1>
  <p class="htr-subtitle">
    This report presents your laboratory results in a clear, visual format.
    Here is a quick guide to understanding each element.
  </p>

  <div class="htr-grid">
    ${cards}
  </div>

  <div class="htr-note">
    <strong>Important:</strong> This report is generated by Smart Health Engine and is intended
    as a summary aid. It does <em>not</em> constitute medical advice. Please consult your
    physician or specialist for interpretation and treatment decisions.
  </div>
</section>`;
    },
};
